" Indentation settings.
set ts=3 sw=3 sts=3 et ai ci

" Turn off annoying A B characters when using arrow keys in insert mode.
" And enable jumping from word to word via ctrl + arrow keys.
set term=xterm

" Don't show line endings. Just put it here to know how to enable.
set nolist

" Show tabs and eol like specified.
"set listchars=tab:▸\ ,eol:¬

" Allow backspace to delete characters created in another mode.
set backspace=indent,eol,start

" Enable undo to undo more than one step.
set nocompatible

" Misc. more general settings.
syntax on
colo slate
set showmode

" Mapping of home and end key.
map <esc>OH <home>
cmap <esc>OH <home>
imap <esc>OH <home>
map <esc>OF <end>
cmap <esc>OF <end>
imap <esc>OF <end>

" Put a new line after ("oo") or before ("OO") the
" current line without changing to insert mode.
nmap oo o<Esc>k
nmap OO O<Esc>j

" START: Enable "set paste" when chaning to insert mode.
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction
" END: Enable "set paste" when chaning to insert mode.

" Above approach does not work within gnu screen, so use F2 to toggle.
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

" Warn via coloring characters for lines longer than 80 characters.
" match ErrorMsg '\%80v.\+'
